fix(Workflow): Avoid bubbling up "Unknown encoding" error to user
temporalio/sdk-node pull request #133
Opened 2021-06-22 14:26 UTC by vkarpov15

## What was changed

I still end up getting the below error pretty regularly when I run a worker:

```
ValueError: Unknown encoding: 0u"Pu
    at CompositeDataConverter.fromPayload (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/@temporalio/workflow/lib/converter/data-converter.js:29:19)
    at Object.arrayFromPayloads (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/@temporalio/workflow/lib/converter/data-converter.js:57:28)
    at /home/val/Workspace/temporalio/samples-node/hello-world/node_modules/@temporalio/worker/lib/worker.js:318:55
    at rxjs_1.pipe.operators_1.mergeScan.state (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/@temporalio/worker/lib/rxutils.js:15:68)
    at MergeScanSubscriber._next (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/operators/mergeScan.js:55:23)
    at MergeScanSubscriber.Subscriber.next (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/Subject.js:60:25)
    at GroupBySubscriber._group (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/operators/groupBy.js:98:19)
    at GroupBySubscriber._next (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/operators/groupBy.js:60:14)
    at GroupBySubscriber.Subscriber.next (/home/val/Workspace/temporalio/samples-node/hello-world/node_modules/rxjs/internal/Subscriber.js:66:18)
```

I don't think this error should propagate to the user, or at least we should log it but not crash the process re: discussion from #110 .

## Why?

I usually end up having to re-run my worker 2-3 times to avoid it crashing due to this error.

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

2021-06-22 14:38 UTC, bergundy requested changes
I don't want us to be silently ignoring this error.
Let's just fail Workflow execution instead of failing the worker.

2021-06-22 16:42 UTC, vkarpov15 commented
@bergundy good call, see 8b593ff for the changes you requested

2021-06-23 00:30 UTC, bergundy approved these changes
LGTM, had one nit.

2021-06-23 00:30 UTC, bergundy commented on packages/worker/src/worker.ts
> +                let args: any[];
nit: let's use `unknown[]`, I'm still trying to remember to use unknown instead of any and TS has had that for a while now.

2021-06-23 19:01 UTC, merged